apiVersion: apps/v1
kind: Deployment
metadata:
  name: okd-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: okd-sample-app
  template:
    metadata:
      labels:
        app: okd-sample-app
    spec:
      containers:
      - name: okd-sample-app
        image: image-registry.openshift-image-registry.svc:5000/simple-web-ap/simple-web-app-TAG:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: okd-sample-app
spec:
  selector:
    app: okd-sample-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: okd-sample-app
spec:
  to:
    kind: Service
    name: okd-sample-app
  port:
    targetPort: 8081
  tls:
    termination: edge
