apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
  labels:
    app: simple-web-app
  namespace: simple-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      securityContext:
        runAsUser: 1000900001   # Use an allowed user ID
        fsGroup: 1000900001   # Allow access to files in the shared volume
      initContainers:
        - name: init-nginx
          image: busybox:1.35.0-uclibc
          command:
            - sh
            - -c
            - |
              mkdir -p /var/cache/nginx/client_temp && chown -R nginx:nginx /var/cache/nginx
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
      containers:
      - name: simple-web-app
        image: image-registry.openshift-image-registry.svc:5000/simple-web-app/simple-web-app-TAG:latest
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: nginx-cache
          emptyDir: {}   # This creates an empty directory for nginx to write to
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
  labels:
    app: simple-web-app
  namespace: simple-web-app
spec:
  selector:
    app: simple-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simple-web-app-route
  namepace: simple-web-app
spec:
  to:
    kind: Service
    name: simple-web-app  # This should match the service name
  port:
    targetPort: 8080  # The port your application is exposing
  tls:
    termination: edge  # Optional: If you want to enable HTTPS
  wildcardPolicy: None
